# Generated by Django 5.2 on 2025-04-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_cin_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='CIN',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
