# Generated by Django 5.2 on 2025-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Carteid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
