# Generated by Django 5.2 on 2025-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_carteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmo',
            name='image1',
            field=models.ImageField(default='photos/25/04/25/pfp.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bienimmo',
            name='image2',
            field=models.ImageField(default='photos/25/04/25/pfp.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bienimmo',
            name='image3',
            field=models.ImageField(default='photos/25/04/25/pfp.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bienimmo',
            name='image4',
            field=models.ImageField(default='photos/25/04/25/pfp.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='bienimmo',
            name='image5',
            field=models.ImageField(default='photos/25/04/25/pfp.jpg', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='locataire_profile_pics/car-rental-vector-13423582.png', null=True, upload_to='locataire_profile_pics/'),
        ),
    ]
