# Generated by Django 5.2.1 on 2025-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmo',
            name='name',
            field=models.CharField(default='nouvelle apartement', max_length=200),
        ),
    ]
