# Generated by Django 5.2.1 on 2025-05-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_bienimmo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_par', to='app.bienimmo')),
            ],
            options={
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'bien')},
            },
        ),
    ]
