# Generated by Django 5.2 on 2025-05-23 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_favoris_id_alter_favoris_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('bien', 'reservation_date', 'reservation_time')},
        ),
    ]
