# Generated by Django 5.2 on 2025-05-23 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bienimmo'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(),
        ),
    ]
