# Generated by Django 5.2 on 2025-05-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
