# Generated by Django 5.2 on 2025-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='locataire_profile_pics/Default.jpg', null=True, upload_to='locataire_profile_pics/'),
        ),
    ]
