# Generated by Django 5.2.1 on 2025-05-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('bien', 'reservation_date', 'reservation_time', 'status')},
        ),
    ]
