# Generated by Django 5.2.1 on 2025-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
